dist: xenial
language: generic

services:
  - mongodb

jdk:
  - openjdk11

env:
  - IMAGE="fairdata/admin-panel-server" \
    IMAGE_TAG="$IMAGE:$TRAVIS_COMMIT" \
    IMAGE_TAG_BRANCH="$IMAGE:"`echo $TRAVIS_BRANCH | sed 's#/#-#g'` \
    IMAGE_TAG_DEVELOP="$IMAGE:develop" \
    IMAGE_TAG_LATEST="$IMAGE:latest"

before_install:
  # 1. Log to public Docker Hub
  - docker login -u "$PUBLIC_DOCKER_USER" -p "$PUBLIC_DOCKER_PASSWORD"

jobs:
  include:
    - stage: build
      script:
        # 1. Install java-backend-common
        - git clone --depth 1 -b $TRAVIS_BRANCH https://github.com/FAIRDataTeam/java-backend-common ./java-backend-common || git clone --depth 1 -b develop https://github.com/FAIRDataTeam/java-backend-common ./java-backend-common
        - cd  ./java-backend-common
        - mvn --quiet --fail-fast install
        - cd ..
        # 2. Build Admin Panel
        - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test
        - mvn --quiet --fail-fast -DskipTests package
        - docker pull $IMAGE_TAG_DEVELOP
        - docker build --cache-from $IMAGE_TAG_DEVELOP -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
      after_success:
        - mvn org.jacoco:jacoco-maven-plugin:report coveralls:report

    - stage: tag
      if: (branch = develop) AND (NOT (type IN (pull_request)))
      install: false
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_DEVELOP
        - docker push $IMAGE_TAG_DEVELOP

    - stage: tag
      if: (branch = master) AND (NOT (type IN (pull_request)))
      install: false
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_LATEST
        - docker push $IMAGE_TAG_LATEST

    - stage: tag
      if: (type = push)
      install: false
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_BRANCH
        - docker push $IMAGE_TAG_BRANCH
